/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplohilo;

import java.awt.Color;
import java.awt.Graphics;
import static java.lang.Thread.sleep;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author diego
 */
public class Reloj2 extends javax.swing.JFrame {

    /**
     * Creates new form reloj2
     */
    Cronometro hilo2;
    //Imagen hilo3;
    Imagen hilo3;
    public Reloj2() {
        initComponents();
        Reloj hilo = new Reloj(jlblhora);
        hilo.start();
        fecha();
        hilo2 = new Cronometro();
        
//        Imagen hilo3;
//        hilo3 = new Imagen();
//        hilo3.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbldia = new javax.swing.JLabel();
        jlblhora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblmin = new javax.swing.JLabel();
        lblhor = new javax.swing.JLabel();
        lblseg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblimagen = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jlbldia.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlbldia.setForeground(java.awt.Color.blue);
        jlbldia.setText("Dia");

        jlblhora.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlblhora.setForeground(java.awt.Color.blue);
        jlblhora.setText("Hora");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbldia, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jlblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbldia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 170, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/diego/Escritorio/images.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        lblmin.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 36)); // NOI18N
        lblmin.setText("00:");

        lblhor.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 36)); // NOI18N
        lblhor.setText("00:");

        lblseg.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 36)); // NOI18N
        lblseg.setText("00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblhor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmin)
                .addGap(18, 18, 18)
                .addComponent(lblseg)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblseg)
                    .addComponent(lblmin)
                    .addComponent(lblhor))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 210, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/diego/Escritorio/rhms4.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 48)); // NOI18N
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setText("Cronometro:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 300, -1));

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon("/home/diego/public_html/GrupoVJ/images/azul5.jpg"))); // NOI18N
        jPanel3.setForeground(java.awt.Color.white);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon("/home/diego/Descargas/1415344880_PauseDisabled.png")); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, 70));

        jButton4.setIcon(new javax.swing.ImageIcon("/home/diego/Descargas/1415344928_StepForwardPressedBlue.png")); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, 70));

        jButton2.setIcon(new javax.swing.ImageIcon("/home/diego/Descargas/1415344868_Play1Pressed.png")); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 90, 70));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel4.setForeground(java.awt.Color.blue);
        jLabel4.setText("Visor de Imagenes");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));
        jPanel3.add(lblimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, -1, -1));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel3.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 90, -1));

        jButton1.setText("Mostrar Nombre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon("/home/diego/Descargas/1415344868_Play1Pressed.png")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon("/home/diego/Descargas/1415344880_PauseDisabled.png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon("/home/diego/Descargas/1415344928_StepForwardPressedBlue.png")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeansProjects/EjemploHilo/src/ejemplohilo/sello-en-3d-de-unl.gif")); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 180, 160));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "su nombre es: " + nombre.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // lienzo1.inicio();
        hilo2.start();
       

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //lienzo1.pausa();
        hilo2.suspend();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // lienzo1.continuar();
        hilo2.resume();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
//      Imagen hilo3;
//       hilo3 = new Imagen();
        hilo3 = new Imagen();   
        hilo3.start();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
//       Imagen hilo3;
//       hilo3 = new Imagen();
       
        hilo3.suspend();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
//       Imagen hilo3;
//       hilo3 = new Imagen();
       
        hilo3.resume();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void fecha() {
        String fecha = Fecha();
        jlbldia.setText(fecha);
    }

    public String Fecha() {

        GregorianCalendar fecha = new GregorianCalendar();
        int dia = fecha.get(fecha.DAY_OF_MONTH);
        int mes = fecha.get(fecha.MONTH);
        int anio = fecha.get(fecha.YEAR);
        String mifecha = String.valueOf(dia) + "/" + nombre(mes) + "/" + String.valueOf(anio);
        return mifecha;

    }

    public String nombre(int mes) {
        switch (mes) {
            case 0:
                return "Enero";

            case 1:
                return "Febrero";
            case 2:
                return "Marzo";
            case 3:
                return "Abril";
            case 4:
                return "Mayo";
            case 5:
                return "Junio";
            case 6:
                return "Julio";
            case 7:
                return "Agosto";
            case 8:
                return "Septiembre";
            case 9:
                return "Octubre";
            case 10:
                return "Noviembre";
            case 11:
                return "Diciembre";

        }
        return "Error";

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reloj2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reloj2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reloj2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reloj2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reloj2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlbldia;
    private javax.swing.JLabel jlblhora;
    private javax.swing.JLabel lblhor;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JLabel lblmin;
    private javax.swing.JLabel lblseg;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
public class Cronometro extends Thread { //una clase que hereda de la clase Thread

        private JLabel lbl;

        public Cronometro() {// Contructor porque la clase es heredada 
            super();
            // this.lbl=lbl;
        }

        public void run() {
            int nuMin = 0; //El Contador de minutos
            int nuSeg = 0; //El Contador de de segundos
            int nuHora = 0; //El Contador de Horas   
            try {//si ocurre un error al dormir el proceso(sleep(999))
                for (;;) { //inicio del for infinito           
                    if (nuSeg != 59) {//si no es el ultimo segundo
                        nuSeg++; //incremento el numero de segundos                                  
                    } else {
                        if (nuMin != 59) {//si no es el ultimo minuto
                            nuSeg = 0;//pongo en cero los segundos 
                            nuMin++;//incremento el numero de minutos
                        } else {//incremento el numero de horas
                            nuHora++;
                            nuMin = 0;//pongo en cero los minutos
                            nuSeg = 0;//pongo en cero los segundos           
                        }
                    }
                    // System.out.println(nuHora+":"+nuMin+":"+nuSeg);//Muestro en pantalla el cronometro
                    lblseg.setText(Integer.toString(nuSeg));
                    lblmin.setText(Integer.toString(nuMin));
                    lblhor.setText(Integer.toString(nuHora));
                    sleep(999);//Duermo el hilo durante 999 milisegundos(casi un segundo, quintandole el tiempo de proceso)
                }//Fin del for infinito             
            } catch (Exception ex) {
                System.out.println(ex.getMessage());//Imprima el error
            }
        }
// public static void main(String[] args) {
////        Cronometro c=new Cronometro(JLabel); //Intancio la clase
////        c.start(); //Ejecuto el metodo run del Thread        
//    }// Fin main
    }//Fin Clas

    public class Imagen extends Thread {
//        private JLabel lblimagen;
//        public Imagen(JLabel lbl){
//              this.lblimagen=lblimagen;
//        }

        public void run() {
            for (int i = 1; i <= 10; i++) {
                if (i == 1) {
                    lblimagen.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeansProjects/EjemploHilo/src/ejemplohilo/The-Walkin.jpg"));
                    try {
                        sleep(5000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Reloj2.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    if (i == 2) {
                        lblimagen.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeansProjects/EjemploHilo/src/ejemplohilo/th.jpg"));
                        try {
                            sleep(5000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Reloj2.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        if (i == 3) {
                            lblimagen.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeansProjects/EjemploHilo/src/ejemplohilo/wallpaperwal.jpg"));
                            try {
                                sleep(5000);
                            } catch (InterruptedException ex) {
                                Logger.getLogger(Reloj2.class.getName()).log(Level.SEVERE, null, ex);
                            }

                        } else {
                            if (i == 4) {
                                lblimagen.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeansProjects/EjemploHilo/src/ejemplohilo/bg.jpg"));
                                try {
                                    sleep(5000);
                                } catch (InterruptedException ex) {
                                    Logger.getLogger(Reloj2.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            } else {
                                if (i == 5) {
                                    lblimagen.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeansProjects/EjemploHilo/src/ejemplohilo/The-Walking-Dead.jpg"));
                                    try {
                                        sleep(5000);
                                    } catch (InterruptedException ex) {
                                        Logger.getLogger(Reloj2.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                } else {
                                    if (i == 6) {
                                        lblimagen.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeansProjects/EjemploHilo/src/ejemplohilo/The-Walking-Dead-cAST.jpg"));
                                        try {
                                            sleep(5000);
                                        } catch (InterruptedException ex) {
                                            Logger.getLogger(Reloj2.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                    } else {
                                        if (i == 7) {
                                            lblimagen.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeansProjects/EjemploHilo/src/ejemplohilo/Walking-Dead_Simpson.jpg"));
                                            try {
                                                sleep(5000);
                                            } catch (InterruptedException ex) {
                                                Logger.getLogger(Reloj2.class.getName()).log(Level.SEVERE, null, ex);
                                            }
                                        } else {
                                            if (i == 8) {
                                                lblimagen.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeansProjects/EjemploHilo/src/ejemplohilo/TWDs4-1.jpg"));
                                                try {
                                                    sleep(5000);
                                                } catch (InterruptedException ex) {
                                                    Logger.getLogger(Reloj2.class.getName()).log(Level.SEVERE, null, ex);
                                                }
                                            } else {
                                                if (i == 9) {
                                                    lblimagen.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeansProjects/EjemploHilo/src/ejemplohilo/nickeon-d6wj10v.jpg"));
                                                    try {
                                                        sleep(5000);
                                                    } catch (InterruptedException ex) {
                                                        Logger.getLogger(Reloj2.class.getName()).log(Level.SEVERE, null, ex);
                                                    }
                                                } else {
                                                    if (i == 10) {
                                                        lblimagen.setIcon(new javax.swing.ImageIcon("/home/diego/NetBeansProjects/EjemploHilo/src/ejemplohilo/The-Wa.jpg"));
                                                        try {
                                                            sleep(5000);
                                                        } catch (InterruptedException ex) {
                                                            Logger.getLogger(Reloj2.class.getName()).log(Level.SEVERE, null, ex);
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }

                            }
                        }

                    }
                }

            }
        }
    }
}
